# Generated by Django 5.2.9 on 2026-01-01 19:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('item_type', models.CharField(choices=[('ALARM', 'Будильник'), ('TIMER', 'Таймер')], max_length=5, verbose_name='Тип')),
                ('alarm_time', models.TimeField(blank=True, help_text='Для будильников', null=True, verbose_name='Время срабатывания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('days_of_week', models.CharField(blank=True, help_text='Укажите дни через запятую (напр. 1,3,5). Оставьте пустым для ежедневного.', max_length=15, verbose_name='Дни недели (Пн=1)')),
                ('timer_duration', models.PositiveIntegerField(blank=True, help_text='Для таймеров', null=True, verbose_name='Длительность (секунды)')),
                ('sound_file', models.FileField(blank=True, help_text='MP3, WAV, OGG файлы', null=True, upload_to='sounds/', verbose_name='Аудиофайл')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Элемент часов',
                'verbose_name_plural': 'Элементы часов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название страны')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Персона (актер/режиссер)',
                'verbose_name_plural': 'Персоны (актеры/режиссеры)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория тега',
                'verbose_name_plural': 'Категории тегов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта/списка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='shared_projects', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Проект / Список задач',
                'verbose_name_plural': 'Проекты / Списки задач',
            },
        ),
        migrations.CreateModel(
            name='ProjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шаблона проекта')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец шаблона')),
            ],
            options={
                'verbose_name': 'Шаблон проекта',
                'verbose_name_plural': 'Шаблоны проектов',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(allow_unicode=True, unique=True)),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Цвет')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='blog.tagcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Задача')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('is_private', models.BooleanField(default=False, verbose_name='Личная задача (видна только создателю)')),
                ('priority', models.CharField(choices=[('LOW', 'Низкий'), ('MEDIUM', 'Обычный'), ('HIGH', 'Высокий')], default='MEDIUM', max_length=6, verbose_name='Приоритет')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Позиция в списке')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='blog.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['is_completed', 'position', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название списка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='shared_task_lists', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_task_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Список задач',
                'verbose_name_plural': 'Списки задач',
            },
        ),
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название шаблонной задачи')),
                ('project_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to='blog.projecttemplate', verbose_name='Шаблон проекта')),
            ],
            options={
                'verbose_name': 'Шаблон задачи',
                'verbose_name_plural': 'Шаблоны задач',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telegram Chat ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
                ('movie_path', models.FileField(blank=True, max_length=500, null=True, upload_to='source_videos', verbose_name='Путь к оригинальному файлу')),
                ('web_player_path', models.FileField(blank=True, max_length=500, null=True, upload_to='movies_web', verbose_name='Путь к веб-версии (mp4)')),
                ('vtt_thumbnails_path', models.FileField(blank=True, max_length=500, null=True, upload_to='previews', verbose_name='Путь к VTT-превью')),
                ('subtitles_path', models.FileField(blank=True, max_length=500, null=True, upload_to='subtitles', verbose_name='Путь к субтитрам')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает обработки'), ('PROCESSING', 'Обрабатывается'), ('READY', 'Готов к просмотру'), ('ERROR', 'Ошибка обработки')], default='PENDING', max_length=10, verbose_name='Статус')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Рейтинг')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность (в секундах)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_type', models.CharField(choices=[('MOVIE', 'Фильм'), ('LESSON', 'Урок')], default='MOVIE', max_length=10, verbose_name='Тип видео')),
                ('processing_progress', models.IntegerField(default=0, verbose_name='Прогресс обработки (%)')),
                ('actors', models.ManyToManyField(blank=True, related_name='filmography_actor', to='blog.person', verbose_name='Актеры')),
                ('countries', models.ManyToManyField(blank=True, to='blog.country', verbose_name='Страны')),
                ('directors', models.ManyToManyField(blank=True, related_name='filmography_director', to='blog.person', verbose_name='Режиссеры')),
                ('genres', models.ManyToManyField(blank=True, to='blog.genre', verbose_name='Жанры')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimestampNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.PositiveIntegerField(verbose_name='Время (секунды)')),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('is_public', models.BooleanField(default=False, verbose_name='Общая заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='blog.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Заметка к видео',
                'verbose_name_plural': 'Заметки к видео',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='blog.video')),
            ],
            options={
                'verbose_name': 'Лог обработки',
                'verbose_name_plural': 'Логи обработки',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_timestamp', models.PositiveIntegerField(default=0, help_text='Последняя позиция просмотра в секундах', verbose_name='Последняя позиция (сек)')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Просмотр завершен')),
                ('watched_at', models.DateTimeField(auto_now=True, verbose_name='Дата последнего просмотра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.video', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'История просмотра',
                'verbose_name_plural': 'Истории просмотров',
                'ordering': ['-watched_at'],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
