# Generated by Django 5.2.9 on 2026-01-03 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание')),
                ('svg_icon', models.TextField(blank=True, help_text='Вставьте сюда полный SVG код иконки', verbose_name='SVG иконка (код)')),
                ('css_class', models.CharField(blank=True, help_text='Например, sticker-blue, sticker-green, sticker-pink', max_length=50, verbose_name='CSS класс для цвета')),
            ],
            options={
                'verbose_name': 'Категория обучения',
                'verbose_name_plural': 'Категории обучения',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='video',
            name='learning_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='blog.learningcategory', verbose_name='Категория обучения'),
        ),
    ]
