# Generated by Django 5.2.9 on 2026-01-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_learningcategory_video_learning_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название файла')),
                ('file_path', models.CharField(max_length=1000, unique=True, verbose_name='Путь к файлу')),
                ('course_name', models.CharField(max_length=255, verbose_name='Название курса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='blog.learningcategory', verbose_name='Категория обучения')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Теги типа файла')),
            ],
            options={
                'verbose_name': 'Учебный материал (ссылка)',
                'verbose_name_plural': 'Учебные материалы (ссылки)',
                'ordering': ['course_name', 'title'],
            },
        ),
    ]
