# Generated by Django 5.2.9 on 2026-01-03 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_learningmaterial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningMaterial',
        ),
    ]
