# Generated by Django 5.2.9 on 2026-01-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_delete_learningmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('absolute_path', models.CharField(max_length=1000, unique=True, verbose_name='Абсолютный путь')),
                ('location_slug', models.CharField(db_index=True, max_length=50, verbose_name='Slug локации')),
                ('relative_path', models.CharField(db_index=True, max_length=1000, verbose_name='Относительный путь')),
                ('is_folder', models.BooleanField(default=False, verbose_name='Это папка?')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Размер (байты)')),
                ('extension', models.CharField(blank=True, max_length=20, verbose_name='Расширение')),
                ('last_modified', models.DateTimeField(verbose_name='Дата изменения')),
                ('indexed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата индексации')),
                ('tags', models.ManyToManyField(blank=True, to='blog.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Проиндексированный элемент',
                'verbose_name_plural': 'Проиндексированные элементы',
                'ordering': ['-is_folder', 'name'],
            },
        ),
    ]
