# Generated by Django 5.2.9 on 2026-01-05 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_indexeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexeditem',
            name='learning_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indexed_items', to='blog.learningcategory', verbose_name='Категория обучения'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('slug', models.SlugField(unique=True, verbose_name='URL (Slug)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('learning_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='blog.learningcategory', verbose_name='Категория обучения')),
                ('tags', models.ManyToManyField(related_name='courses', to='blog.tag', verbose_name='Теги / Технологии')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_files/', verbose_name='Файл')),
                ('name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='blog.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Файл курса',
                'verbose_name_plural': 'Файлы курсов',
            },
        ),
    ]
