# Generated by Django 5.2.9 on 2026-01-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_indexeditem_learning_category_course_coursefile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursefile',
            options={'ordering': ['ordering', 'name'], 'verbose_name': 'Файл курса', 'verbose_name_plural': 'Файлы курсов'},
        ),
        migrations.AddField(
            model_name='course',
            name='source_path',
            field=models.CharField(blank=True, help_text='Укажите абсолютный путь к папке, чтобы просканировать файлы автоматически.', max_length=1000, null=True, verbose_name='Путь к папке курса (D:\\...)'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='external_path',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Путь к файлу на диске'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='coursefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_files/', verbose_name='Загруженный файл'),
        ),
    ]
