# Generated by Django 5.2.10 on 2026-01-29 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseImportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_path', models.CharField(help_text='Пример: D:\\Education\\My_C_Courses. Каждая папка внутри станет отдельным Курсом.', max_length=500, verbose_name='Путь к папке с курсами')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запуска')),
                ('import_log', models.TextField(blank=True, help_text='Здесь появится отчет после сохранения.', verbose_name='Лог выполнения')),
                ('tag_to_add', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.tag', verbose_name='Добавить тег (опционально)')),
                ('target_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.learningcategory', verbose_name='В какую категорию положить?')),
            ],
            options={
                'verbose_name': '⚙️ Массовый импорт курсов',
                'verbose_name_plural': '⚙️ Массовый импорт курсов',
                'ordering': ['-created_at'],
            },
        ),
    ]
