# Generated by Django 5.2.10 on 2026-02-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_courseimportsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefile',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность (сек)'),
        ),
    ]
