# Generated by Django 5.2.10 on 2026-02-09 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_studyplan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='course_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.coursefile', verbose_name='Файл курса'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.video', verbose_name='Видео'),
        ),
    ]
