# Generated by Django 5.2.10 on 2026-02-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_searchconfig_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID на TMDb'),
        ),
    ]
