# Generated by Django 5.2.11 on 2026-02-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_video_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='file_ext',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Расширение'),
        ),
    ]
