# Generated by Django 5.2.11 on 2026-02-10 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_video_file_ext'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'ordering': ['-updated_at'], 'verbose_name': 'История просмотра', 'verbose_name_plural': 'Истории просмотров'},
        ),
        migrations.RenameField(
            model_name='watchhistory',
            old_name='watched_at',
            new_name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='watchhistory',
            unique_together={('user', 'video')},
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='timestamp',
            field=models.IntegerField(default=0, verbose_name='Остановился на секунде'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='course_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.coursefile', verbose_name='Старый файл курса'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='blog.video', verbose_name='Видео/Урок'),
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='last_timestamp',
        ),
    ]
