# Generated by Django 5.2.11 on 2026-02-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_watchhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Длительность (сек)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='movie_path',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='source_videos', verbose_name='Путь к оригиналу'),
        ),
        migrations.AlterField(
            model_name='video',
            name='vtt_thumbnails_path',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='previews', verbose_name='Путь к VTT'),
        ),
    ]
