# Generated by Django 5.2.11 on 2026-02-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_video_duration_alter_video_movie_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='last_viewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда смотрел'),
        ),
        migrations.AddField(
            model_name='video',
            name='learning_status',
            field=models.CharField(choices=[('new', '🆕 Новый'), ('in_progress', '▶️ Смотрю'), ('completed', '✅ Изучено')], default='new', max_length=20, verbose_name='Статус обучения'),
        ),
    ]
