# Generated by Django 5.2.11 on 2026-02-12 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_video_last_viewed_at_video_learning_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_videos', to=settings.AUTH_USER_MODEL, verbose_name='В избранном у'),
        ),
        migrations.AddField(
            model_name='video',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_videos', to=settings.AUTH_USER_MODEL, verbose_name='Посмотреть позже'),
        ),
    ]
