# Generated by Django 5.2.11 on 2026-02-12 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_video_favorites_video_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название сериала')),
                ('original_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оригинальное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('poster', models.ImageField(blank=True, upload_to='posters/shows/', verbose_name='Постер')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='TMDb ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='episode_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер серии'),
        ),
        migrations.AddField(
            model_name='video',
            name='season_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер сезона'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_type',
            field=models.CharField(choices=[('MOVIE', 'Фильм'), ('LESSON', 'Урок'), ('CLIP', 'Клип'), ('EPISODE', 'Эпизод сериала')], default='MOVIE', max_length=10, verbose_name='Тип видео'),
        ),
        migrations.AddField(
            model_name='video',
            name='tv_show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='blog.tvshow', verbose_name='Сериал'),
        ),
    ]
