# Generated by Django 5.2.11 on 2026-02-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_tvshow_video_episode_number_video_season_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvshow',
            name='original_title',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='tmdb_id',
        ),
        migrations.AddField(
            model_name='tvshow',
            name='show_type',
            field=models.CharField(choices=[('SERIES', 'Сериал'), ('ANIME', 'Аниме'), ('CARTOON', 'Мультсериал')], default='SERIES', max_length=20, verbose_name='Тип'),
        ),
    ]
