# Generated by Django 5.2.11 on 2026-02-16 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_remove_tvshow_original_title_remove_tvshow_tmdb_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='reward_coins',
            field=models.IntegerField(default=5, verbose_name='Награда Монет'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='reward_xp',
            field=models.IntegerField(default=10, verbose_name='Награда XP'),
        ),
        migrations.AddField(
            model_name='tasktemplate',
            name='rewards_claimed',
            field=models.BooleanField(default=False, verbose_name='Награда получена'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coins',
            field=models.IntegerField(default=0, verbose_name='Монеты (J-Coins)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1, verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='Опыт (XP)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RewardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название награды')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('cost', models.IntegerField(verbose_name='Цена (монет)')),
                ('icon', models.CharField(default='bi-gift', max_length=50, verbose_name='Bootstrap иконка')),
                ('available_for', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Доступно для')),
            ],
            options={
                'verbose_name': 'Награда магазина',
                'verbose_name_plural': 'Магазин наград',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_fulfilled', models.BooleanField(default=False, verbose_name='Выдано родителями')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.rewarditem')),
            ],
        ),
    ]
