# Generated by Django 5.2.11 on 2026-02-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_userprofile_options_tasktemplate_reward_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reward_coins',
            field=models.IntegerField(default=10, verbose_name='Монеты за задачу'),
        ),
        migrations.AddField(
            model_name='task',
            name='reward_xp',
            field=models.IntegerField(default=50, verbose_name='Опыт за задачу'),
        ),
        migrations.AddField(
            model_name='task',
            name='rewards_claimed',
            field=models.BooleanField(default=False, verbose_name='Награды выданы (защита от дублей)'),
        ),
    ]
