# Generated by Django 6.0.4 on 2026-04-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_task_reward_coins_task_reward_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_approved',
            field=models.BooleanField(default=True, verbose_name='Одобрено родителем'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Повторяющаяся'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='repeat_days',
            field=models.IntegerField(default=7, verbose_name='Повторять каждые X дней'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='was_notified',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
    ]
