# Generated by Django 6.0.4 on 2026-04-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_purchase_is_approved_tasklist_is_recurring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='was_notified',
        ),
        migrations.AddField(
            model_name='task',
            name='was_notified',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
    ]
