# Generated by Django 5.2.9 on 2026-04-19 20:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_remove_tasklist_was_notified_task_was_notified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название типа')),
                ('icon', models.CharField(default='bi-record-circle', max_length=50, verbose_name='Иконка (Bootstrap)')),
                ('color', models.CharField(default='#0d6efd', max_length=10, verbose_name='Цвет (HEX)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_types', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Тип события',
                'verbose_name_plural': 'Типы событий',
            },
        ),
        migrations.CreateModel(
            name='MetricGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название цели')),
                ('target_value', models.IntegerField(verbose_name='Целевое значение')),
                ('current_value', models.IntegerField(default=0, verbose_name='Текущий прогресс')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('event_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.eventtype', verbose_name='Связанная категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.CreateModel(
            name='TrackerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Событие (Изжога, Отжимания, Пицца)')),
                ('value', models.IntegerField(default=1, verbose_name='Значение / Количество')),
                ('note', models.TextField(blank=True, verbose_name='Заметка')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время события')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.eventtype', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог трекера',
                'verbose_name_plural': 'Логи трекера',
                'ordering': ['-timestamp'],
            },
        ),
    ]
