# Generated by Django 6.0.4 on 2026-04-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_eventtype_metricgoal_trackerevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerevent',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='trackerevent',
            name='value',
            field=models.IntegerField(default=1, verbose_name='Значение'),
        ),
    ]
