# Generated by Django 6.0.6 on 2026-07-07 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_purchaselog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
                ('description', models.TextField(blank=True, verbose_name='Описание или ссылка')),
                ('event_date', models.DateTimeField(verbose_name='Дата и время события')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='events_covers/', verbose_name='Обложка')),
                ('sound_file', models.FileField(blank=True, null=True, upload_to='sounds/', verbose_name='Особый звук (опционально)')),
                ('is_notified', models.BooleanField(default=False, verbose_name='Уведомление сработало')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Плановое событие',
                'verbose_name_plural': 'Плановые события',
                'ordering': ['event_date'],
            },
        ),
    ]
