# Generated by Django 6.0.6 on 2026-07-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_plannedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedevent',
            name='is_important',
            field=models.BooleanField(default=False, verbose_name='Супер важное'),
        ),
    ]
