# Generated by Django 6.0.6 on 2026-07-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_plannedevent_is_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyBoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя Босса (например: Ржавый Танк)')),
                ('max_hp', models.IntegerField(default=1000, verbose_name='Максимальная броня (HP)')),
                ('current_hp', models.IntegerField(default=1000, verbose_name='Текущая броня (HP)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bosses/', verbose_name='Аватар Босса')),
                ('reward_coins', models.IntegerField(default=100, verbose_name='Награда за уничтожение (Монеты)')),
                ('is_defeated', models.BooleanField(default=False, verbose_name='Побежден')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Босс (Family Hub)',
                'verbose_name_plural': 'Боссы (Family Hub)',
            },
        ),
        migrations.AddField(
            model_name='childtask',
            name='damage',
            field=models.IntegerField(default=50, verbose_name='Урон по боссу'),
        ),
    ]
