# Generated by Django 6.0.6 on 2026-09-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_familyboss_childtask_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio_tracks',
            field=models.JSONField(blank=True, default=list, verbose_name='Аудиодорожки'),
        ),
        migrations.AddField(
            model_name='video',
            name='subtitle_tracks',
            field=models.JSONField(blank=True, default=list, verbose_name='Субтитры'),
        ),
    ]
