# Generated by Django 6.0.6 on 2026-09-04 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_video_audio_tracks_video_subtitle_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='course_covers/', verbose_name='Обложка курса'),
        ),
    ]
