server {
    listen 80;
    server_name localhost;
    charset utf-8;

    # Лимит на размер загружаемого файла (20 ГБ)
    client_max_body_size 20G;

    # --- 1. ВАЖНО: Подключение типов файлов ---
    # Без этой строки браузер не поймет, что css это стили, а mp4 это видео.
    include /etc/nginx/mime.types;

    # Дополнительно прописываем тип для субтитров
    types {
        text/vtt vtt;
    }

    # --- 2. ИСХОДНИКИ ФИЛЬМОВ (AVI, MKV) ---
    # Перехватываем ссылки вида /media/source_movies/...
    # И направляем их в папку /source_movies/ (которая смотрит на D:\mediaserver\Movies)
    location /media/source_movies/ {
        alias /source_movies/;
        # autoindex on; # Раскомментируйте, если хотите видеть список файлов в браузере
        add_header Accept-Ranges bytes; # Разрешаем докачку и частичную загрузку
    }

    # --- 3. ГОТОВЫЕ МЕДИА (MP4, Обложки) ---
    # Все остальные запросы к /media/ идут в папку Ready
    location /media/ {
        alias /code/media/;
        expires 30d;
        add_header Cache-Control "public";
        add_header Accept-Ranges bytes; # Важно для перемотки видео
    }

    # --- 4. СТАТИКА (CSS, JS для админки) ---
    location /static/ {
        alias /code/staticfiles/;
        expires 1y;
        add_header Cache-Control "public";
    }

    # --- 5. ОСНОВНОЙ САЙТ (Django) ---
    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
    }
    # 👇 ДОБАВЛЯЕМ ЭТОТ БЛОК ДЛЯ КУРСОВ 👇
    location /media/source_courses/ {
        # Важно: alias должен указывать на папку ВНУТРИ контейнера
        alias /source_courses/;
        autoindex on; # Разрешает просмотр списка файлов (опционально)
    }
}